export const GET_DOG_DETAIL_LOADING = "GET_DOG_DETAIL_LOADING";
export const GET_DOG_DETAIL_SUCCESS = "GET_DOG_DETAIL_SUCCESS";
export const GET_DOG_DETAIL_ERROR = "GET_DOG_DETAIL_ERROR";

export const GET_DOGS_LOADING = "GET_DOGS_LOADING";
export const GET_DOGS_SUCCESS = "GET_DOGS_SUCCESS";
export const GET_DOGS_ERROR = "GET_DOGS_ERROR";
export const FILTER_BY = "FILTER_BY";

export const GET_TEMPERAMENTS_LOADING = "GET_TEMPERAMENTS_LOADING";
export const GET_TEMPERAMENTS_SUCCESS = "GET_TEMPERAMENTS_SUCCESS";
export const GET_TEMPERAMENTS_ERROR = "GET_TEMPERAMENTS_ERROR";

export const RESET_FILTER = "RESET_FILTER";

export const baseUrl = process.env.REACT_APP_BASE_URL;

export const dogsPerPage = 8;
